Registry.require("crcrc helper uri layout/default/htmlutil i18n layout/default/layout_helper".split(" "),function(){var z=rea.FEATURES,w=Registry.get("crcrc").cr,f=Registry.get("crcrc").crc,A=Registry.get("helper"),p=Registry.get("layout/default/htmlutil"),E=Registry.get("uri"),n=Registry.get("i18n"),x=Registry.get("layout"),y=Registry.get("layout/default/layout_helper"),q=y.images,r=3;if(z.RUNTIME.MOBILE)try{window.matchMedia("(orientation: portrait)").matches&&(r=1)}catch(t){}x.render(function(){var t=
{},F;y.addStyle();var R=function(b,a){var c=[];if(a.sub_menu_item){if(a.tabId&&(F=a.tabId),a.items.length){var d=f("table","actiontable at_"+a.name,"actiontable-"+a.name);G(d,a.items);c.push(d)}}else{var g=null;a.image?g=p.createIcon(q.get(a.image),a.name,a.id,null,""):a.enabler&&(g=p.createIcon(q.get(t.enabled?"button_ok":"cancel"),a.name,a.uuid,null,""));g&&c.push(g);if(a.url||a.urls){for(var g=w("span",a.name,a.id,"urls"),m=a.urls||[a],e=0;e<m.length;e++){var h=m[e],k=document.createElement("span");
k.textContent=h.name;var l=a.urls?k:b;l.url=h.url;l.newtab=h.newtab;$(l).addClass("clickable").on("click auxclick",function(a){B(this.url,this.newtab);a.preventDefault()});g.appendChild(k);e<m.length-1&&(h=document.createElement("span"),h.textContent=" | ",g.appendChild(h))}c.push(g)}else if(a.globalhint)H(a.options);else if(a.button)e=f("span",a.display||"",a.name,a.id,"bu",!0),e.textContent=a.name,b.key=a.id,b.warning=a.warning,b.reload=a.reload,b.data=a.data,b.addEventListener("click",function(){var a=
!0;this.warning&&(a=N(this.warning));a&&O(this.key,{reload:this.reload,data:this.data})}),$(b).addClass("clickable"),c.push(e);else if(a.userscript){d=f("table","",a.name,a.uuid,"tw");g=f("tr","",a.name,a.uuid,"tw_tr1");m=[g];e=f("div","clickable"+(a.active_count?"":" not_executed")+(a.deleted?" was_deleted":""),a.name,a.uuid,"ai");if(a.uuid){var u=[],k=null,k=a.blacklisted||a.foisted?"enabler_warning":a.enabled?a.contexter?"enabler_enabled enabler_later":"enabler_enabled":"enabler_disabled",l=a.blacklisted||
a.foisted||(a.enabled?n.getMessage("Enabled"):n.getMessage("Disabled")),h=function(b){if(b&&(0!=b.button||b.ctrlKey||b.metaKey))return B(rea.extension.getURL("options.html")+"#nav="+this.key,!0),b.stopPropagation(),b.preventDefault(),!1;a.foisted?C(a.uuid,"whitewash",!0):C(a.uuid,"enabled",!a.enabled)},k=p.createEnabler(k,a.uuid,"enabled",{append:"enabled",disabled:a.blacklisted||a.deleted,title:l},h),l=f("td","",a.name,a.uuid,"tw_td1");g.appendChild(l);l.appendChild(k);k=f("div","script_name",a.name,
a.uuid,"name");k.textContent=n.getTranslation(a,"name");e.appendChild(k);e.uuid=a.uuid;e.key=a.uuid;if(!a.deleted&&!a.blacklisted){$(e).on("click auxclick",h);var h=n.getMessage("Edit"),l=p.createIcon(q.get("edit"),"",a.uuid,"edit_script",h),r=f("span","clickable",a.name,a.uuid,"edit_script");r.setAttribute("title",h);r.textContent=h;u.push({always_visible:!1,id:"edit_script",img:l,text:r,oc:function(b){B(rea.extension.getURL("options.html")+"#nav="+a.uuid,!0)}})}a.blacklisted||a.foisted?(b.setAttribute("title",
a.blacklisted||a.foisted),$(e).addClass("crossedout")):k.title=a.active_count?n.getMessage("This_script_was_executed_0count0_times",a.active_count):a.all_time_active_count?n.getMessage("This_script_was_executed_0count0_times_but_is_not_active_anymore",a.all_time_active_count):n.getMessage("This_script_was_not_executed_yet");h=f("td","",a.name,a.uuid,"tw_td2");g.appendChild(h);h.appendChild(e);a.nnew||a.system||!a.abuse||(h=p.createIcon(q.get("flag"),"",a.uuid,"issue",n.getMessage("Report_an_issue_to_the_script_hoster_")),
e=f("span","clickable",a.name,a.uuid,"action_issue_expl"),e.textContent=n.getMessage("Report_an_issue_to_the_script_hoster_").split(/[\.\(]+/)[0],u.push({always_visible:!1,id:"action_issue_expl",img:h,text:e,oc:function(){I(a.uuid,"hoster")}}));a.nnew||a.system||!a.support||(h=p.createIcon(q.get("bug"),"",a.uuid,"bug",n.getMessage("Report_a_bug")),e=f("span","clickable",a.name,a.uuid,"action_issue_expl"),e.textContent=n.getMessage("Report_a_bug"),u.push({always_visible:!1,id:"action_issue_expl",img:h,
text:e,oc:function(){I(a.uuid,"author")}}));var v={};a.active_urls&&a.active_urls.forEach(function(b){var d=E.parse(b).hostname;if(!v[d]){v[d]=!0;var c="/"+E.getRegExpFromMatch("*://*."+d+"/*")+"/";if(!a.override||-1==a.override.use_excludes.indexOf(c)){d=n.getMessage("Exclude_0domain0",d);b=p.createIcon(q.get("no"),"",a.uuid,"domain"+b,d);var g=f("span","clickable",a.name,a.uuid,"action_domain");g.setAttribute("title",d);g.textContent=d;u.push({always_visible:!1,id:"action_domain",img:b,text:g,oc:function(b){C(a.uuid,
"add_excludes",[c])}})}}});if(a.menu_cmds){var D;try{D=new RegExp("^"+A.escapeForRegExp(a.name)+"[ -:+/]*")}catch(M){console.log(M)}a.menu_cmds.forEach(function(d){var c=f("span","clickable",a.name,a.uuid,"menucmd_"+a.id);c.setAttribute("title",a.name);var g=D?d.name.replace(D,""):d.name;c.textContent=g;var e=function(){P(d.id,function(){z.ACTIONMENU.CLOSE_ALLOWED&&window.close()})};if(d.accessKey){var h=d.accessKey[0].toUpperCase();if(Q(h,e,b)){var k=new RegExp(h,"i"),m=c.textContent.search(k),l=
[];-1==m&&(c.textContent+=" ("+h+")",m=c.textContent.search(k));l.push({text:c.textContent.substr(0,m)});l.push({text:c.textContent.substr(m,1),class:"underlined"});l.push({text:c.textContent.substr(m+1)});c.textContent="";l.forEach(function(a){var b=f("span",a.class||"",d.id,a);b.textContent=a.text;c.appendChild(b)})}else console.warn("Registering keyboard shortcut for '"+d.name+"' failed")}u.push({always_visible:!0,id:a.id,img:p.createIcon(q.get(d.image),g,d.id,null,""),text:c,oc:e})})}if(!a.deleted&&
u.length){var x=[];u.forEach(function(b){var d=a.uuid+b.id,c=f("tr","scriptmenu"+(b.always_visible?" always_visible":""),a.name,a.uuid,"tw_tr1"),g=f("td","clickable",d,"tw_tdn",1,!0),d=f("td","clickable",d,"tw_tdn",2,!0);d.setAttribute("colspan","2");d.addEventListener("click",b.oc);d.appendChild([b.img,b.text]);c.appendChild([g,d]);x.push(c)});e=f("div","actionenablercol",a.name,a.uuid,"actionenablercol");h=f("i","actionenabler ifdisabled clickable far fa-"+q.get("enabler"),a.name,a.uuid,"actionenabler");
k=f("i","actionenabler ifenabled clickable far fa-"+q.get("enabler_enabled"),a.name,a.uuid,"actionenabler_enabled");$("body").get(0).addEventListener("click",function(){$(d).removeClass("show_scriptmenu");y.removeClass("enabled")},!0);var y=$(e);$(h,k,e).click(function(a){y.toggleClass("enabled");$(d).toggleClass("show_scriptmenu");a.stopPropagation()});e.appendChild([h,k]);m=m.concat(x);h=f("td","",a.name,a.uuid,"tw_td3");g.appendChild(h);h.appendChild(e)}}d.appendChild(m);c.push(d)}else e=w("span",
a.name,a.id,"ai"),e.textContent=a.name,c.push(e)}return c},G=function(b,a,c){Object.keys(a).forEach(function(d){var g=a[d];if(!b)if(c[g.pos])g.items&&g.items.length&&$(c[g.pos]).show();else{console.warn("Warn(cAm): unknown pos "+g.pos);return}var f=(d=b||c[g.pos])?w("tr",g.name,g.uuid||g.id,"outer"):null,e=R(f,g);if(e&&e.length){d.appendChild(f);var h;for(d=0;h=e[d];d++){var k=d==e.length-1?3-d:0,l=w("td","actiontd",g.name,g.uuid||g.id,d);0<k&&l.setAttribute("colspan",k);h&&l.appendChild(h);f.appendChild(l)}}})},
J=function(b){var a=$("#action"),c=w("div");c.setAttribute("id","action");a.replaceWith(c);var d=f("table","actionlayout","actionlayout");c.appendChild(d);c=f("tr","actionpostr","hor");a=f("td","actionpostd","hor_west");c.appendChild(a);d.appendChild(c);var g=f("table","actionregion noborder ar_top","top"),m=f("table","actionregion noborder ar_right","right"),e,h=f("table","actionregion noborder ar_left","left"),k=f("table","actionregion noborder ar_bottom","bottom");if(2<Math.min(t.action_menu_columns,
r)){e=f("table","actionregion noborder ar_center","center");var l=f("td","actionpostd","hor_center"),d=f("td","actionpostd","hor_east");l.appendChild(e);c.appendChild(l);c.appendChild(d)}else 1<Math.min(t.action_menu_columns,r)?(e=m,d=f("td","actionpostd","hor_east"),c.appendChild(d)):(e=h,d=a);$([e,m]).hide();a.appendChild(g);d.appendChild(m);a.appendChild(h);a.appendChild(k);G(null,b,{top:g,left:h,center:e,right:m,bottom:k})},B=function(b,a){try{var c=function(){a&&z.ACTIONMENU.CLOSE_ALLOWED&&window.close()};
a?sendMessage({method:"newTab",url:b},c):rea.tabs.getSelected(null,function(d){rea.tabs.sendMessage(d.id,{method:"loadUrl",url:b,newtab:a},c)})}catch(d){console.warn("lU:",d)}},N=function(b){var a=confirm(b.msg),c={};a&&b.ok?c=b.ok:!a&&b.cancel&&(c=b.cancel);if(b.ok||b.cancel)a=!0;c.url&&sendMessage({method:"newTab",url:c.url},function(a){});return a},H=function(b){var a,c=b.key||"general";(a=K[c])&&$(a).remove();K[c]=p.createGobalHint(A.copy(b,{instant:!0}),$("body > div.status")[0])},I=function(b,
a,c){try{sendMessage({method:"reportAnIssue",uuid:b,to:a},function(a){c&&c()})}catch(d){console.warn("raI:",d)}},O=function(b,a){try{sendMessage({method:"buttonPress",name:b,data:a.data},function(b){a.reload&&rea.page.reload()})}catch(c){console.warn("rSU:",c)}},v={},S=function(b,a,c){document.body.addEventListener("keydown",function(a){a.altKey||a.ctrlKey||a.shiftKey||Object.keys(v).forEach(function(b){(b=v[b])&&a.keyCode==b.key&&b.cb.apply(b.elem||window,[])})},!1)},Q=function(b,a,c){b=b.charCodeAt(0);
if(v[b])return console.log("MenuCmdKeyListener: ...failed!"),!1;v[b]={key:b,cb:a,elem:c};return!0},P=function(b,a){try{sendMessage({method:"execMenuCmd",id:b},function(b){a&&a()})}catch(c){console.warn("Error(eMC):",c)}},C=function(b,a,c){try{b={method:"modifyScriptOptions",uuid:b},a&&""!=a&&(b[a]=c),sendMessage(b,function(a){document.getElementById("action").innerHTML="";a&&(a.i18n&&n.setLocale(a.i18n),a.items&&(a.options&&(t=A.assign(t,a.options)),J(a.items)))})}catch(d){console.warn("Error(mSo): "+
d.message)}},T=function(b,a){var c=Date.now(),d=b.min_delay;sendMessage({method:"loadTree",referrer:b.referrer,layout:b.layout,available_columns:r,uuid:b.uuid,tabId:b.tabId},function(b){b.options&&(t=A.assign(t,b.options));b.layout&&x.applyTheme(b.layout);b.i18n&&n.setLocale(b.i18n);var f=Date.now()-c,e=function(){a(b)};!d||f>=d?e():window.setTimeout(e,d-f)})},K={};rea.extension.onMessage.addListener(function(b,a,c){"update"==b.method?L():"status"==b.method?(H(b.options),c({})):console.log('onMessage: Unknown method "'+
b.method+'"')});var L=window.main=function(){T({referrer:"actions",min_delay:z.ACTIONMENU.MIN_DELAY,layout:!0,tabId:F},function(b){if(b.options&&b.options.layout_user_css){var a=document.createElement("style");a.innerHTML=b.options.layout_user_css;(document.head||document.body||document.documentElement||document).appendChild(a)}S();J(b.items)})};L()})});
