#!/bin/bash
#Checking if user is root
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

echo 'Installing Base System'
cfdisk
mkswap /dev/sda1
mkfs.ext4 /dev/sda2
mount /dev/sda2 /mnt
pacstrap /mnt base
genfstab -p /mnt >> /mnt/etc/fstab
arch-chroot /mnt
echo Arch > /etc/hostname
ln -sf /usr/share/zoneinfo/Europe/Copenhagen /etc/localtime
echo en_US.UTF-8 UTF-8 >> /etc/locale.gen
locale-gen
echo LANG=en_US.UTF-8 > /etc/locale.conf
mkinitcpio -p linux
echo pwrp > pass.tmp
echo pwrp >> pass.tmp
cat pwrp | passwd
rm pass.tmp
pacman -S syslinux base-devel dhclient vim sudo
#syslinux-install_update -i -a -m
echo 'Done installing base system please reboot'
