# autogenerated by txs
#include:latex-document
#include:latex-mathsymbols
#include:tex
\begin{tightemize}#S
\custombold{arg1}#S
\descript{arg1}#S
\end{tightemize}#S
\lastupdated#S
\location{arg1}#S
\namesection{arg1}{arg2}{arg3}#S
\runsubsection{arg1}#S
\sectionsep#S
