# autogenerated by txs
\BeforeSubString{arg1}{arg2}#S
\BehindSubString{arg1}{arg2}#S
\CountSubStrings{arg1}{arg2}#S
\IfBeforeSubStringEmpty{arg1}{arg2}#S
\IfBehindSubStringEmpty{arg1}{arg2}#S
\IfCharInString#S
\IfSubStringInString{arg1}{arg2}#S
\SubStringsToCounter{arg1}{arg2}{arg3}#S
\su#S
